### ISSUE TITLE
Multiple Drill Cluster not connecting using sqlalchemy

### ISSUE THREAD

**Issue by dwevedivaibhav** [JohnOmernik/sqlalchemy-drill#84]
Hi Team,

I am trying to connect multiple cluster of drill (Distributed mode of drill) but not able to connect , look like not supporting passing multiple ip in connection string with (comma or semicolon).

Can some body can help on this ?
any leads will be appreciated

**Comment by jnturton** [comment]
If you're using sqlalchemy-drill with JDBC (or ODBC) then you don't need to put multiple Drillbit addresses into the URL. Instead, use a ZooKeeper based URL.

https://drill.apache.org/docs/using-the-jdbc-driver/#using-the-jdbc-url-for-a-random-drillbit-connection

However, if you're using sqlalchemy-drill with REST (drill+sadrill://) then you'll have to specify an individual Drillbit. If you're concerned about efficient use of the whole cluster for query execution there's no need to be because this is unaffected by which Drillbit receives the query. If you're concerned about high availability then you can either switch to JDBC/ODBC with a ZooKeeper URL, or you can put a load balancer with a liveness probe (I'd expect nginx would work) in front of the REST APIs of all of your Drillbits.
